In [27]:
img_names = []
with open('img_ids.txt') as in_file:
    for line in in_file:
        line = line.strip()
        img_names.append(line)

In [28]:
import pandas as pd

In [29]:
df1 = pd.read_csv('../data/processed/metadata.csv')

In [30]:
df1['id'] = df1.index

# 

In [31]:
import numpy as np

In [32]:
vectors = np.load('vectors.npy')

In [33]:
vectors.shape

(35930, 512)

In [34]:
len(img_names)

35930

In [39]:
img_names_= ['_'.join(n.split('/')[-1].split('_')[1:]).split('.')[0] for n in img_names]

In [40]:
df = df1.copy()

In [41]:
df['id'] = -1

In [42]:
df['NAME_'] = df['NAME'].apply(lambda x: x.split('.')[0])

In [43]:
for i, n in enumerate(img_names_):
    df.loc[df['NAME_'] == n, 'id'] = i

In [44]:
df[df['id'] == -1]

Empty DataFrame
Columns: [MMS ID, IE PID, REP PID, FL PID, NAME, SIZE, EXT, LABEL, DIGI NUMBER, FL PID (IIIF), SEQ (OCR), Uniform title, Main title, Variant title, publication_place, Publisher, year, Material type, Colour, General note, Copyright status of physical object, Copyright status of digital object, Terms of use, Author (main entry), Author (added entry), Group title, Language, Country of publication, Resolver URL, Label (Library Call number), mango_path, mango_output_path, server_path, id, title, side, public_url, teneo_link, Lat, Lng, NAME_]
Index: []

[0 rows x 41 columns]

In [46]:
np.array(df['id'].values)

array([30723, 30726, 30730, ..., 20682, 20686, 20567])

In [47]:
np.save('../webapplication/services/backend/vectors.npy',vectors[np.array(df['id'].values)])

In [48]:
vectors[df['id'].values, :]

array([[-0.5016155 ,  0.6077143 ,  0.01994955, ..., -0.2875953 ,
        -0.03529226,  0.4695928 ],
       [-0.17832659,  0.311575  ,  0.22563255, ...,  0.06355028,
        -0.21149758, -0.07386951],
       [-0.32692203,  0.15611827, -0.20075977, ...,  0.3296623 ,
         0.06702857,  0.05279856],
       ...,
       [-0.455882  ,  0.23034021,  0.10284189, ...,  0.47333908,
        -0.08295902, -0.2662745 ],
       [-0.27648178, -0.0627953 , -0.09098797, ...,  0.15747601,
        -0.25907072, -0.0638373 ],
       [-0.22421217, -0.11936583,  0.2696256 , ...,  0.39112142,
        -0.06340607, -0.06096066]], dtype=float32)

In [49]:
df['id'].values[0]

30723

In [50]:
vectors[30723]

array([-5.01615524e-01,  6.07714295e-01,  1.99495517e-02,  2.72513926e-02,
       -3.12572345e-02, -3.17393467e-02, -2.06811219e-01,  5.71501315e-01,
       -2.87162811e-01, -3.24346721e-02, -2.78179854e-01,  7.85411447e-02,
       -5.84365129e-01,  9.23580900e-02, -1.19996756e-01, -2.62037098e-01,
       -2.70017892e-01, -1.58016503e-01, -2.73583710e-01,  2.11122021e-01,
        1.02186644e+00, -6.81790784e-02,  8.25150907e-02, -1.34613961e-02,
        4.24893320e-01, -2.17455849e-02,  1.26071721e-01,  1.90162152e-01,
       -3.15932453e-01, -3.58268023e-01,  3.78328599e-02,  6.65272772e-02,
       -1.07676029e-01,  6.27572238e-01,  6.16235584e-02,  2.47925878e-01,
       -2.32701153e-02, -1.88973472e-01, -5.17616272e-01,  6.88531995e-01,
       -2.78629392e-01, -2.71722317e-01,  1.93918452e-01, -2.90660053e-01,
        1.21826842e-01, -2.56410432e+00, -6.46136701e-02,  2.75288001e-02,
       -3.26310471e-03, -3.80935669e-01,  9.22262967e-02,  4.65700984e-01,
        2.62618631e-01,  

In [51]:
img_names[30723]

'/scratch/leuven/338/vsc33847/DATASET_3/IE9004132/REP9004136/FL9004137_DIGI_0020_022735_R.tif.LQ.small.jpg'

In [ ]:
[28118, 12865, 23487, 17931, 6959, 4642, 21724, 35906, 16909, 14253]

In [100]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width',None)

In [102]:
for t in df[df['id'].isin([28118, 12865, 23487, 17931, 6959, 4642, 21724, 35906, 16909, 14253])]['public_url']:
    print(t)

https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992367829501488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992258867901488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992504404101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9990243430101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992614600101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992498906101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9991245210101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992131706901488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992334462101488
https://kuleuven.limo.libis.be/view/delivery/thumbnail/32KUL_KUL/9992512508401488
